---
dependencies:
  cloud_firestore: ^3.1.8
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: ^4.6.1
  intl: ^0.17.0
  logger: ^1.1.0
  permission_handler: ^8.3.0
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter:
  assets:
    - assets/
  uses-material-design: true
name: barcode_scanner
publish_to: none
version: 1.0.0+1